# .github/workflows/mkdocs-static-site-generation.yml

name: Deploy MkDocs Site to GitHub Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # These permissions are required to allow the workflow to publish to GitHub Pages
    permissions:
      contents: write # Needed for multirepo to clone other repos, and for gh-pages deployment
      pages: write
      id-token: write

    steps:
      # 1. Checkout the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # The multirepo plugin needs the full git history to fetch other repos
          fetch-depth: 0

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python version
          cache: 'pip' # Caches pip dependencies for faster builds

      # 3. Install dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Build the MkDocs site
      # The multirepo plugin will automatically run here, cloning the other repos
      - name: Build MkDocs site
        run: mkdocs build

      # 5. Deploy the built site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The folder the action should deploy.
          publish_dir: ./site